#!/bin/sh -e
for py in py-attrs py-jinja py-markupsafe py-pygments py-pypeg py-yaml; do (
    cd "$py"
    python setup.py build
    python setup.py install --prefix=/usr --root="$1"
) done
# Remove DBus dependency
cd qutebrowser
sed -i "s/'PyQt5.QtDBus'/#'PyQt5.QtDBus'/" misc/earlyinit.py
sed -i "s/from PyQt5.QtDBus/#from PyQt5.QtDBus/" browser/webengine/notification.py
sed -i "s/QDBusArgument, Q/#QDBusArgument, Q/" browser/webengine/notification.py
sed -i "s/webenginedownloads, notification/webenginedownloads/" browser/webengine/webenginesettings.py
sed -i "s/notification.init()/#notification.init()/" browser/webengine/webenginesettings.py
sed -i "s/if notification.bridge/#if notification.bridge/" browser/webengine/webenginesettings.py
sed -i "s/notification.bridge.in/#notification.bridge.in/" browser/webengine/webenginesettings.py
cd ..
python setup.py build
python setup.py install --prefix=/usr --root="$1"
