#!/bin/sh -e
sip-build --no-make --no-dbus-python --confirm-license
# python configure.py \
    # --confirm-license

cd build
make

# idk, hopefully one of them works
make -j1 INSTALL_ROOT="$1" DESTDIR="$1" install
