#!/bin/sh

# https://kisslinux.xyz/package-manager#6.0

# https://github.com/kisslinux/kiss/commit/d765dbd043d5a69a15875f2cd0ff81cdaaa2d97f
TYPE=$1
PKG=$2

source /etc/profile

case $TYPE in
	pre-build) echo "$PKG" > $ASSETS_DIR/kiss_build ;;
	build-fail) echo "$PKG: build failed" > $ASSETS_DIR/kiss_build ;;

	# -f: no error if file doesn't exist
	post-install) rm -f $ASSETS_DIR/kiss_build ;;
	post-build) rm -f $ASSETS_DIR/kiss_build ;;
esac

# short/statusbar will then use kiss_build to display, using xsetroot
